More FreeBSD work.

diff --git a/templates/FreeBSD/cloud-set-guest-password-freebsd.j2 b/templates/FreeBSD/cloud-set-guest-password-freebsd.j2
--- a/templates/FreeBSD/cloud-set-guest-password-freebsd.j2
+++ b/templates/FreeBSD/cloud-set-guest-password-freebsd.j2
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!env bash
 #
 # FreeBSD
 # Modify this line to specify the user (default is root)
@@ -6,60 +6,57 @@ user=root
 
 # Add your DHCP lease folders here
 WGET=/usr/local/bin/wget
-DHCP_FOLDERS="/var/db/dhclient.leases.*"
 password_received=0
 file_count=0
 error_count=0
 
-for DHCP_FILE in $DHCP_FOLDERS
-do
-	if [ -f $DHCP_FILE ]
+. /usr/share/cloudstack/cloudstack-common-functions
+find_lease()
+
+PASSWORD_SERVER_IP=$(grep dhcp-server-identifier $LEASE_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')
+
+if [ -n $PASSWORD_SERVER_IP ]
+then
+	logger -t "cloud" "Found password server IP $PASSWORD_SERVER_IP in $LEASE_FILE"
+	logger -t "cloud" "Sending request to password server at $PASSWORD_SERVER_IP"
+	password=$($WGET -q -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $PASSWORD_SERVER_IP:8080)
+	password=$(echo $password | tr -d '\r')
+
+	if [ $? -eq 0 ]
 	then
-		file_count=$((file_count+1))
-		PASSWORD_SERVER_IP=$(grep dhcp-server-identifier $DHCP_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')
+		logger -t "cloud" "Got response from server at $PASSWORD_SERVER_IP"
 
-		if [ -n $PASSWORD_SERVER_IP ]
-		then
-			logger -t "cloud" "Found password server IP $PASSWORD_SERVER_IP in $DHCP_FILE"
-			logger -t "cloud" "Sending request to password server at $PASSWORD_SERVER_IP"
-			password=$($WGET -q -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $PASSWORD_SERVER_IP:8080)
-			password=$(echo $password | tr -d '\r')
-
-			if [ $? -eq 0 ]
-			then
-				logger -t "cloud" "Got response from server at $PASSWORD_SERVER_IP"
-
-				case $password in
-				
-				"")					logger -t "cloud" "Password server at $PASSWORD_SERVER_IP did not have any password for the VM"
-									continue
-									;;
-				
-				"bad_request")		logger -t "cloud" "VM sent an invalid request to password server at $PASSWORD_SERVER_IP"
-									error_count=$((error_count+1))
-									continue
-									;;
-									
-				"saved_password") 	logger -t "cloud" "VM has already saved a password from the password server at $PASSWORD_SERVER_IP"
-									continue
-									;;
-									
-				*)					logger -t "cloud" "VM got a valid password from server at $PASSWORD_SERVER_IP"
-									password_received=1
-									break
-									;;
-									
-				esac
-			else
-				logger -t "cloud" "Failed to send request to password server at $PASSWORD_SERVER_IP"
-				error_count=$((error_count+1))
-			fi
-		else
-			logger -t "cloud" "Could not find password server IP in $DHCP_FILE"
-			error_count=$((error_count+1))
-		fi
+		case $password in
+		
+		"")								logger -t "cloud" "Password server at $PASSWORD_SERVER_IP did not have any password for the VM"
+							continue
+							;;
+		
+		"bad_request")		logger -t "cloud" "VM sent an invalid request to password server at $PASSWORD_SERVER_IP"
+							error_count=$((error_count+1))
+							continue
+							;;
+							
+		"saved_password") logger -t "cloud" "VM has already saved a password from the password server at $PASSWORD_SERVER_IP"
+							continue
+							;;
+							
+		*)								logger -t "cloud" "VM got a valid password from server at $PASSWORD_SERVER_IP"
+							password_received=1
+							break
+							;;
+							
+		esac
+	else
+		logger -t "cloud" "Failed to send request to password server at $PASSWORD_SERVER_IP"
+		error_count=$((error_count+1))
 	fi
-done
+else
+	logger -t "cloud" "Could not find password server IP in $LEASE_FILE"
+	error_count=$((error_count+1))
+fi
+
+
 
 if [ "$password_received" == "0" ]
 then
diff --git a/templates/FreeBSD/cloud-set-guest-sshkey-freebsd.j2 b/templates/FreeBSD/cloud-set-guest-sshkey-freebsd.j2
--- a/templates/FreeBSD/cloud-set-guest-sshkey-freebsd.j2
+++ b/templates/FreeBSD/cloud-set-guest-sshkey-freebsd.j2
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!env bash
 #
 # Init file for SSH Public Keys Download Client for FreeBSD
 #
@@ -9,36 +9,27 @@
 user=root
 
 WGET=/usr/local/bin/wget
-# Add your DHCP lease folders here
-DHCP_FOLDERS="/var/db/dhclient.leases.*"
 
 keys_received=0
 file_count=0
 
-for DHCP_FILE in $DHCP_FOLDERS
-do
-	if [ -f $DHCP_FILE ]
-	then
-		file_count=$((file_count+1))
-		SSHKEY_SERVER_IP=$(grep dhcp-server-identifier $DHCP_FILE | tail -1 | awk '{print $NF}' | tr -d '\;')
+. /usr/share/cloudstack/cloudstack-common-functions
+find_lease()
 
-		if [ -n $SSHKEY_SERVER_IP ]
-		then
-			logger -t "cloud" "Sending request to ssh key server at $SSHKEY_SERVER_IP"
+SSHKEY_SERVER_IP=$(grep dhcp-server-identifier $LEASE_FILE | uniq | tail -1 | awk '{print $NF}' | tr -d '\;')
 
-			publickey=$($WGET -t 3 -T 20 -O - http://$SSHKEY_SERVER_IP/latest/public-keys 2>/dev/null)
+if [ -n $SSHKEY_SERVER_IP ]; then
+    logger -t "cloud" "Sending request to ssh key server at $SSHKEY_SERVER_IP"
 
-			if [ $? -eq 0 ]
-			then
-				logger -t "cloud" "Got response from server at $SSHKEY_SERVER_IP"
-				keys_received=1
-				break
-			fi
-		else
-			logger -t "cloud" "Could not find ssh key server IP in $DHCP_FILE"
-		fi
-	fi
-done
+    publickey=$($WGET -t 3 -T 20 -O - http://$SSHKEY_SERVER_IP/latest/public-keys 2>/dev/null)
+
+    if [ $? -eq 0 ]; then
+        logger -t "cloud" "Got response from server at $SSHKEY_SERVER_IP"
+        keys_received=1
+    fi
+else
+    logger -t "cloud" "Could not find ssh key server IP in $LEASE_FILE"
+fi
 
 # did we find the keys anywhere?
 if [ "$keys_received" == "0" ]
